### ISSUE TITLE
Update or remove About section

### ISSUE THREAD

**Issue by davidneudorfer** [papertrails/papertrails.co-static#7]
Currently About has a timeline view. Do we want to keep that or move to a paragraph style view?

![image](https://cloud.githubusercontent.com/assets/547876/14905875/5a561832-0d83-11e6-8b7d-0d626dd27cde.png)

**Comment by anishavasandani** [comment]
Let's flag this for the future. Let's switch to paragraph view.

Paper Trails Co has one goal in mind: make traveling easier and more meaningful for our users. If your idea of a great trip includes eating like a local, knowing where to venture next instead of staring at your phone, and having experiences tailored to your travel preferences, you're in the right place. If that means making sure you'll visit a new coffee shop every morning, so be it. If it means venturing out of our comfort zone, we can handle it.
